# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class WishItem(scrapy.Item):
    # define the fields for your item here like:

    name = scrapy.Field()
    url = scrapy.Field()
    rating = scrapy.Field()
    rating_count = scrapy.Field()
    seller = scrapy.Field()
    seller_rating = scrapy.Field()
    gender = scrapy.Field()
    img_1 = scrapy.Field()
    img_2 = scrapy.Field()
    img_3 = scrapy.Field()
    img_4 = scrapy.Field()
    img_5 = scrapy.Field()
    img_6 = scrapy.Field()
    img_7 = scrapy.Field()
    img_8 = scrapy.Field()
    img_9 = scrapy.Field()
    id = scrapy.Field()
    total_inventory = scrapy.Field()
    num_bought = scrapy.Field()
    brand = scrapy.Field()
    description = scrapy.Field()

    v1_price = scrapy.Field()
    v1_price_discount = scrapy.Field()
    v1_min_fullfillment_time = scrapy.Field()
    v1_max_fullfillment_time = scrapy.Field()
    v1_inventory = scrapy.Field()
    v1_size = scrapy.Field()
    v1_color = scrapy.Field()
    v1_shipping_fee = scrapy.Field()

    v2_price = scrapy.Field()
    v2_price_discount = scrapy.Field()
    v2_min_fullfillment_time = scrapy.Field()
    v2_max_fullfillment_time = scrapy.Field()
    v2_inventory = scrapy.Field()
    v2_size = scrapy.Field()
    v2_color = scrapy.Field()
    v2_shipping_fee = scrapy.Field()

    v3_price = scrapy.Field()
    v3_price_discount = scrapy.Field()
    v3_min_fullfillment_time = scrapy.Field()
    v3_max_fullfillment_time = scrapy.Field()
    v3_inventory = scrapy.Field()
    v3_size = scrapy.Field()
    v3_color = scrapy.Field()
    v3_shipping_fee = scrapy.Field()

    v4_price = scrapy.Field()
    v4_price_discount = scrapy.Field()
    v4_min_fullfillment_time = scrapy.Field()
    v4_max_fullfillment_time = scrapy.Field()
    v4_inventory = scrapy.Field()
    v4_size = scrapy.Field()
    v4_color = scrapy.Field()
    v4_shipping_fee = scrapy.Field()

    v5_price = scrapy.Field()
    v5_price_discount = scrapy.Field()
    v5_min_fullfillment_time = scrapy.Field()
    v5_max_fullfillment_time = scrapy.Field()
    v5_inventory = scrapy.Field()
    v5_size = scrapy.Field()
    v5_color = scrapy.Field()
    v5_shipping_fee = scrapy.Field()

    v6_price = scrapy.Field()
    v6_price_discount = scrapy.Field()
    v6_min_fullfillment_time = scrapy.Field()
    v6_max_fullfillment_time = scrapy.Field()
    v6_inventory = scrapy.Field()
    v6_size = scrapy.Field()
    v6_color = scrapy.Field()
    v6_shipping_fee = scrapy.Field()

    v7_price = scrapy.Field()
    v7_price_discount = scrapy.Field()
    v7_min_fullfillment_time = scrapy.Field()
    v7_max_fullfillment_time = scrapy.Field()
    v7_inventory = scrapy.Field()
    v7_size = scrapy.Field()
    v7_color = scrapy.Field()
    v7_shipping_fee = scrapy.Field()

    v8_price = scrapy.Field()
    v8_price_discount = scrapy.Field()
    v8_min_fullfillment_time = scrapy.Field()
    v8_max_fullfillment_time = scrapy.Field()
    v8_inventory = scrapy.Field()
    v8_size = scrapy.Field()
    v8_color = scrapy.Field()
    v8_shipping_fee = scrapy.Field()

    v9_price = scrapy.Field()
    v9_price_discount = scrapy.Field()
    v9_min_fullfillment_time = scrapy.Field()
    v9_max_fullfillment_time = scrapy.Field()
    v9_inventory = scrapy.Field()
    v9_size = scrapy.Field()
    v9_color = scrapy.Field()
    v9_shipping_fee = scrapy.Field()

    v10_price = scrapy.Field()
    v10_price_discount = scrapy.Field()
    v10_min_fullfillment_time = scrapy.Field()
    v10_max_fullfillment_time = scrapy.Field()
    v10_inventory = scrapy.Field()
    v10_size = scrapy.Field()
    v10_color = scrapy.Field()
    v10_shipping_fee = scrapy.Field()

    v11_price = scrapy.Field()
    v11_price_discount = scrapy.Field()
    v11_min_fullfillment_time = scrapy.Field()
    v11_max_fullfillment_time = scrapy.Field()
    v11_inventory = scrapy.Field()
    v11_size = scrapy.Field()
    v11_color = scrapy.Field()
    v11_shipping_fee = scrapy.Field()

    v12_price = scrapy.Field()
    v12_price_discount = scrapy.Field()
    v12_min_fullfillment_time = scrapy.Field()
    v12_max_fullfillment_time = scrapy.Field()
    v12_inventory = scrapy.Field()
    v12_size = scrapy.Field()
    v12_color = scrapy.Field()
    v12_shipping_fee = scrapy.Field()

    v13_price = scrapy.Field()
    v13_price_discount = scrapy.Field()
    v13_min_fullfillment_time = scrapy.Field()
    v13_max_fullfillment_time = scrapy.Field()
    v13_inventory = scrapy.Field()
    v13_size = scrapy.Field()
    v13_color = scrapy.Field()
    v13_shipping_fee = scrapy.Field()

    v14_price = scrapy.Field()
    v14_price_discount = scrapy.Field()
    v14_min_fullfillment_time = scrapy.Field()
    v14_max_fullfillment_time = scrapy.Field()
    v14_inventory = scrapy.Field()
    v14_size = scrapy.Field()
    v14_color = scrapy.Field()
    v14_shipping_fee = scrapy.Field()

    v15_price = scrapy.Field()
    v15_price_discount = scrapy.Field()
    v15_min_fullfillment_time = scrapy.Field()
    v15_max_fullfillment_time = scrapy.Field()
    v15_inventory = scrapy.Field()
    v15_size = scrapy.Field()
    v15_color = scrapy.Field()
    v15_shipping_fee = scrapy.Field()

